import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/Header";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Deglaze",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <AuthProvider>
            <html lang="en">
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center`}
                >
                    <div className="py-8">
                        <Header />
                        <div className="flex gap-[100px]">
                            <NavBar />
                            {children}
                        </div>
                    </div>
                </body>
            </html>
        </AuthProvider>
    );
}
